[package]
name = "mc-server-view"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenvy = "0.15.6"
mc-query = "0.2.0"
rocket = { version = "0.5.0-rc.2", features = ["json"] }
thiserror = "1.0.38"
